services:
  
  tomcat-server:
    image: tomcat-app:latest
    container_name: 'tomcat-container'
    ports:
      - 7001:8080
      
  reverse-proxy:
    image: nginx
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8081:80
